version: "3.5"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=wannsea.eu #optional
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
      - PEERDNS=8.8.8.8 #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - /home/wannsea/wireguard:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    networks:
      vpn:
        ipv4_address: 172.67.0.2
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    entrypoint: ["/bin/bash", "-c", "ip route add 192.168.0.0/16 via 172.67.0.3 && /init"]
    restart: unless-stopped

  ipsec:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    cap_add:
      - NET_ADMIN
    env_file:
      - /home/wannsea/ipsec/vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - /home/wannsea/ipsec:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vpn:
        ipv4_address: 172.67.0.3
    entrypoint: ["/bin/bash", "-c", "ip route add 10.13.13.0/24 via 172.67.0.2 && /opt/src/run.sh"]

networks:
  vpn:
    name: vpn
    driver: bridge
    ipam:
      config:
        - subnet: 172.67.0.0/16
          gateway: 172.67.0.1
