name: VPN Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - run: docker compose down -t 0
      - run: docker compose up -d --build
